services:
  mongo:
    image: mongo:4.2.5
    # No ports exposed for security
  myapp:
    build:
      context: ./app
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      DOCKER_DB: true
    # No ports exposed, Nginx handles it
    depends_on:
      - mongo
  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # For HTTP -> HTTPS redirect or standard HTTP
      - "443:443" # For HTTPS
    volumes:
      # Mount the specific host config file OVER the default container config file
      - /etc/nginx/sites-available/unknown2.cse312.dev:/etc/nginx/conf.d/default.conf:ro
      # Mount Let's Encrypt directory for certificates (if using production)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Mount dhparams file (if using production)
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
    depends_on:
      - myapp
    restart: always