services:
  mongo:
    image: mongo:4.2.5
    # No ports exposed for security
  myapp:
    build:
      context: ./app # Point build context to the app directory
    env_file:
      - .env # Load environment variables from .env file in the root
    volumes:
      # Map the host logs directory to the container logs directory
      - ./logs:/app/logs
    environment:
      # WAIT_HOSTS: mongo:27017 # Keep or remove depending on if you use a wait script
      DOCKER_DB: true # Example variable if needed
      # MONGO_URI is now loaded from .env file via env_file
    # Remove ports mapping, Nginx will handle external exposure
    # ports:
    #  - '8080:8080'
    depends_on:
      - mongo # Ensure mongo starts before the app attempts to connect
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Only expose HTTP port 80 locally
      - "443:443" # Add HTTPS port for production
    volumes:
      # Mount the host's production nginx config instead of the local dev config
      - /etc/nginx/sites-available/unknown1.cse312.dev:/etc/nginx/conf.d/default.conf:ro # Adjusted for production
      # Mount Let's Encrypt directory for certificates (if using production)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Mount dhparams file (if using production)
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
    depends_on:
      - myapp
    restart: always 