services:
  mongo:
    image: mongo:4.2.5
    # No ports exposed for security
  myapp:
    build:
      context: ./app # Point build context to the app directory
    env_file:
      - .env # Load environment variables from .env file in the root
    volumes:
      # Map the host logs directory to the container logs directory
      - ./logs:/app/logs
    environment:
      # WAIT_HOSTS: mongo:27017 # Keep or remove depending on if you use a wait script
      DOCKER_DB: true # Example variable if needed
      # MONGO_URI is now loaded from .env file via env_file
    # Remove ports mapping, Nginx will handle external exposure
    # ports:
    #  - '8080:8080'
    depends_on:
      - mongo # Ensure mongo starts before the app attempts to connect
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Only expose HTTP port 80 locally
      # - "443:443" # Comment out or remove HTTPS port
    volumes:
      # Mount the LOCAL nginx config relative to docker-compose.yml
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      # Remove or comment out the server's absolute paths
      # - /etc/nginx/sites-available/unknown2.cse312.dev:/etc/nginx/conf.d/default.conf:ro
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      # - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
    depends_on:
      - myapp
    restart: always 